#!/usr/bin/perl

use strict; 
use warnings;
use Data::Dumper;
use Template;
use JSON;
use autodie qw(:all);
use Imager::QRCode;
use PDF::API2::Simple;

use FindBin;
use lib "$FindBin::Bin/lib";

use PayPal;

# enable autoflush
$|++;

if (!defined($ARGV[0])) {
  print "Please specify invoice number to generate from data directory.\n";
  die;
}

my $id = $ARGV[0];

if ( ! -f "data/$id.json") {
  die "The file id \"$id\" does not exist!\n";
}

local $/;
open( my $fh, '<', "data/$id.json" );
my $json_text = <$fh>;
close($fh);

my $data = decode_json( $json_text );

my $tt = Template->new;

$data->{id} = $id;

my @items;

my $int = 0;
foreach my $item ( @{$data->{items}}) {
  $data->{price_total} += $item->{price};
  $data->{items}->[$int]->{descr} = pack("A60", $data->{items}->[$int]->{descr}); 
  $int++;
};

# generate QR image

if (defined($data->{from}->{paypal})) {
  print "Generating QR code...($data->{from}->{paypal})\n";
  $data->{paypal_link} = PayPal::pp_link($data);
  PayPal::pp_qr($id, $data->{paypal_link});
}

# generate UK PDF
my $pdf = PDF::API2::Simple->new( file => "out/$id.pdf" );
$pdf->add_font('Courier');
$pdf->add_page();

$pdf->set_font('Courier',20);
$pdf->x(72);
$pdf->y(650);
$pdf->text("Invoice no. $id");
$pdf->set_font('Courier',10);
$pdf->x(72);
$pdf->y(600);
$pdf->text("From:");
$pdf->next_line();
$pdf->text("$data->{from}->{name}");
$pdf->next_line();
$pdf->text("$data->{from}->{address}->{street}");
$pdf->next_line();
$pdf->text("$data->{from}->{address}->{city}");
$pdf->next_line();
$pdf->text("$data->{from}->{address}->{postcode}");
$pdf->next_line();
$pdf->text("Bank: $data->{from}->{bank_details}");
$pdf->next_line();
$pdf->text("$data->{from}->{contact}");

$pdf->x(350);
$pdf->y(600);
$pdf->text("To:");
$pdf->next_line();
$pdf->text("$data->{to}->{name}");
$pdf->next_line();
$pdf->text("$data->{to}->{address}->{street}");
$pdf->next_line();
$pdf->text("$data->{to}->{address}->{city}");
$pdf->next_line();
$pdf->text("$data->{to}->{address}->{postcode}");
$pdf->next_line();
$pdf->text("$data->{to}->{address}->{country}");
$pdf->next_line();
$pdf->text("Registration no.: $data->{to}->{registration_no}");

$pdf->x(40);
$pdf->y(480);
$pdf->set_font('Courier',8);
my $y = 420;
foreach my $item ( @{$data->{items}}) {
  $pdf->x(72);
  $pdf->y($y);
  $pdf->text($item->{descr});
  $pdf->x(450);
  $pdf->y($y);
  $pdf->text($item->{price}." ".$data->{currency});
  $y = $y - 9;
}

$pdf->x(300);
$pdf->y(280);
$pdf->set_font('Courier',10);
$pdf->text("Total amount:");
$pdf->x(450);
$pdf->y(280);
$pdf->text($data->{price_total}." ".$data->{currency});

$pdf->x(300);
$pdf->y(265);
$pdf->text("Total owed:");
$pdf->x(450);
$pdf->y(265);
$pdf->text($data->{price_total}." ".$data->{currency});

$pdf->x(72);
$pdf->y(200);
$pdf->text("Goods delivered on: $data->{date}");
$pdf->next_line;
$pdf->text("Date of invoice: $data->{date}");

$pdf->x(72);
$pdf->y(150);
$pdf->text("Thank you for your custom.");

if ( -f "tmp/${id}_qr.jpeg") { 
  $pdf->x(300);
  $pdf->y(80);
  $pdf->image("tmp/${id}_qr.jpeg");
  $pdf->next_line();
  $pdf->x(300);
  $pdf->link( $data->{paypal_link}, 'Click here or scan the QR code');
  $pdf->next_line();
  $pdf->x(300);
  $pdf->link( $data->{paypal_link}, 'to pay by Card or credit card.');
}

$pdf->save();

print "Done.\n";
